### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by snicki13** [tarkant/svg-dom-arrows#13]
Hey there,

you may not be aware of it, but in absence of a permissive license in this repository, you implicitly reserve all rights to this code, so no one is allowed to use it legally.
See here: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

The forked project is licensed unter MIT, would consider using this license here as well?

Best regards

Dominik

**Comment by tarkant** [comment]
Hello @snicki13,

First I would like to apologise for the very long delay. I didn't notice the issue's notification on my github.
Secondly, thank you very much for raising this issue. Honestly I thought that setting the licence to MIT in the `package.json` was enough.

This is done, the project has been forked from an MIT repo and will stay MIT.

Thank you again, I'll update my other repos too.

Kind regards.
