### ISSUE TITLE
TypeScript types are missing from NPM package

### ISSUE THREAD

**Issue by Flambe** [tarkant/svg-dom-arrows#29]
In the `package.json` it specifies that TypeScript types should be available:

https://github.com/tarkant/svg-dom-arrows/blob/1a07606b8296451e9197eb495b058b6137076c39/package.json#L12

But the NPM package does not have these types:

![image](https://user-images.githubusercontent.com/2080851/235972268-81463410-ee53-4313-81ea-0ca8e339cc27.png)

**Comment by tarkant** [comment]
Hello @Flambe, I've just published version [2.0.5](https://github.com/tarkant/svg-dom-arrows/releases/tag/2.0.5) on github and npm that fixes the typings issue you've reported.

Please give it a check and feel free to reopen the issue or create a new one if it's not solved.

Thank you again for your valuable feedback.
Cheers!

**Comment by Flambe** [comment]
Hey @tarkant, thank you for the quick fix! I can check properly tomorrow but if [NPM](https://www.npmjs.com/package/svg-dom-arrows?activeTab=code) is correct then it looks great to me!
