### ISSUE TITLE
Curvy path renders in an unexpected direction when the points are close

### ISSUE THREAD

**Issue by Flambe** [tarkant/svg-dom-arrows#30]
I'm trying to add lines between two lists that are side by side. Instead of going sideways to start like I'd expect, CurvyPath goes down/up then across. SquarePath is how I expected CurvyPath to go.

https://stackblitz.com/edit/svg-dom-arrows-demo-qfdmsb?file=index.ts

![image](https://user-images.githubusercontent.com/2080851/235975673-8caeb2c8-355e-4bfe-bf24-2c7ee9ac275d.png)

**Comment by tarkant** [comment]
Hello @Flambe, indeed this is an unexpected behavior, good call.
I'll give it a look and let you know.

**Comment by Flambe** [comment]
Thank you for the fixes! Looks much better (though I do need to work on the positions slightly I think)
 
![image](https://github.com/tarkant/svg-dom-arrows/assets/2080851/8d9e375a-97e4-4d4b-a838-b6dd79457e3d)

**Comment by tarkant** [comment]
> Thank you for the fixes! Looks much better (though I do need to work on the positions slightly I think)
> 
> I'm very used to getting that feeling looking at my old code haha
> 
> ![image](https://user-images.githubusercontent.com/2080851/244757173-8d9e375a-97e4-4d4b-a838-b6dd79457e3d.png)

Awesome! Please don't hesitate to create another issue if you notice anything. Thank you again for the great feedback!
