### ISSUE TITLE
Elements that are side by side result in a line that isn't visible

### ISSUE THREAD

**Issue by Flambe** [tarkant/svg-dom-arrows#31]
Elements that are side by side result in a line that isn't visible. On all of the examples I'd expect a flat line between the two elements (maybe a curved line for arc? :shrug:)

The code is exactly the same as #30 except I've removed one div from the left lists.

https://stackblitz.com/edit/svg-dom-arrows-demo-171mer?file=index.html

![image](https://user-images.githubusercontent.com/2080851/235976260-af2e2990-68f8-426b-86f0-a125e09482ac.png)

I just found this library today, it's really simple to use. Thank you! :D

**Comment by tarkant** [comment]
Hello @Flambe, I'm really happy this library comes useful to you!
Thank you for your detailed feedback, seems that there is a weird issue with the offset calculations.
I'll try to fix this ASAP, I'll keep you updated.

**Comment by tarkant** [comment]
Hello @Flambe, apologies for the very long delay. I've published [v2.0.6-beta.1](https://www.npmjs.com/package/svg-dom-arrows/v/2.0.6-beta.1) on npm, I'd like you to give it a try and see if it's fixed.

The issue was rather unexpected, when the SVG path is a straight line, the method that calculates the SVG size (`LinePath.getSVGProportions()`) returns 0 which makes anything inside it invisible. Setting it to a minimum of 1px seems to fix it.

**Comment by tarkant** [comment]
> I added it to the reproduction example above and it looks to be working :D https://stackblitz.com/edit/svg-dom-arrows-demo-qg2kvg?file=index.ts (not sure why they dip slightly, but they render which is great!)

Yes that's the first thing I've tested and how I caught the bug basically. An odd behaviour haha.
I'll be looking forward to your feedback. Meanwhile I'll checkout #30.

Cheers!

**Comment by Flambe** [comment]
Definitely looks better! From what I can see, the thick right hand side is because I'm overlapping the arrows and the haven't lined up exactly correctly, probably something I can fix by adjusting the the `top` slightly.

Thank you for the fix!

old:
![image](https://github.com/tarkant/svg-dom-arrows/assets/2080851/bf9b7adb-d326-4bda-9e41-5e5139af551a)

new:
![image](https://github.com/tarkant/svg-dom-arrows/assets/2080851/c19bad00-7f39-4f39-ab71-7edb668e7a0a)

**Comment by tarkant** [comment]
@Flambe Awesome! Glad it's fixed. I'll release v2.0.6 and check #30 ASAP.
Cheers!
