### ISSUE TITLE
Allowing custom classes on lines

### ISSUE THREAD

**Issue by rbozan** [tarkant/svg-dom-arrows#33]
In TailwindCSS you often use classes for styling instead of using `style`. It would be wise to allow to add a custom class so we can easily change the stroke color for example.

**Comment by tarkant** [comment]
Hello @rbozan , thank you for taking the time to provide your feedback, I'll take care of this issue as well as #32 and report back to you once I've prepared a beta package.

Kind regards!

**Comment by tarkant** [comment]
Hello again @rbozan, I've prepared version [v2.1.0-beta.1](https://www.npmjs.com/package/svg-dom-arrows/v/2.1.0-beta.1) with the possibility to set custom CSS classes as follows (excerpt from the README):

```ts
/**
 * This function just returns an `SVGMarkerElement` that's already pre-styled and so on
 */
const createMarker  = (): SVGMarkerElement => {
  const arrow = document.createElementNS(SVGNS, 'path');
  const marker = document.createElementNS(SVGNS, 'marker');

  arrow.setAttribute('d', 'M 0 0 L 10 5 L 0 10 z');
  arrow.setAttribute('style', 'fill:white;stroke-width:0.801524;stroke-miterlimit:4;stroke-dasharray:none');

  marker.setAttribute('id', 'marker1'); // <== Make sure to set an id attribute
  /**
   * The below attributes and values are specific to this marker, you'll have to know how markers work
   * to really do something fun. For now you'll have to deal with it manually but I might work on an SVG
   * marker utility.
   */
  marker.setAttribute('refX', '5');
  marker.setAttribute('refY', '5');
  marker.setAttribute('viewBox', '0 0 10 10');
  marker.setAttribute('orient', 'auto-start-reverse'); // <== There is a trick here, be sure to read after the code snippet
  marker.setAttribute('markerWidth', '6');
  marker.setAttribute('markerHeight', '6');
  marker.appendChild(arrow);

  return marker;
};

const s = document.querySelector('.case-1');
const e = document.querySelector('.case-4');
const line = new LinePath({
  start: {
    element: s,
    position: {
      top: .45,
      left: 1,
    },
    markerId: '#marker1', // <== We attribute the marker id for the start of the path
  },
  end: {
    element: e,
    position: {
      top: .5,
      left: 0,
    },
    markerId: '#marker1',  // <== We attribute the same marker to the end of the path
  },
  style: 'stroke:white;stroke-width:4;fill:transparent',
  appendTo: document.body,
  markers: [createMarker()], // Supply your markers as an array to this option
  // Custom CSS classes that you can add for additional styling
  // CSS classes should be as follows: `foo bar baz` and NOT `.foo.bar.baz`
  customClass: {
    container: `container-${idx} foo bar`,
    svgPath: `path-${idx} baz`,
    svgElement: `element-${idx}`,
  }
}, true);
```

The library will simply use the native `Element.classList.add()` function to add the CSS classes that you input.

I hope this will also help you solve #32 . Keep me updated!

**Comment by tarkant** [comment]
Hi again @rbozan, awesome news! Very happy that it works.

For the usage with Svelte sadly yes it's outside of the scope of the library. I might have the perfect idea for this but I don't want to get your hopes high, I'll tag you on an issue here if I have a conclusive result.

For now, [v2.1.0](https://www.npmjs.com/package/svg-dom-arrows/v/2.1.0) is live! 🎉

**Comment by tarkant** [comment]
Hello @rbozan ,

I played around with Svelte and I seem to be able to partially work around how it works. [Check out this StackBlitz I've created.](https://stackblitz.com/edit/vitejs-vite-iuyro1?file=src%2FApp.svelte) It's not a very elegant solution but I guess that it can be wrapped with a svelte component that will take the start and end node and show the path.

I've updated the package to [v2.1.2](https://www.npmjs.com/package/svg-dom-arrows/v/2.1.2) and exposed:
- `svgElement: SVGSVGElement` (It's not a typo, it's really SVGSVGElement haha) it contains the `<svg...>` tag
- `svgPathLine: SVGPathElement` it contains the `<path...>` tag
- `containerDiv: HTMLDivElement` the container div

As you can see in the StackBlitz example, I'm copying the style of the SVG element and div to fix the positioning then binding the path, the transition works like a charm.

Of course one can just create custom CSS classes with nice transitions but honestly I like how it seamlessly worked with Svelte.

Please let me know if you'd like me to improve something. I'll soon add the Svelte exemple in the readme too!

Kind regards.

**Comment by tarkant** [comment]
Hi again @rbozan , yeah I'm honestly impressed! I had fun yesterday playing around with it, Svelte is really neat! As I'm professionally working on VueJS a lot of stuff felt similar. Thanks for peaking my curiosity about it!

As for the workaround, I admit it's a little hacky but yeah, it works.

Keep it up and best wishes!

**Comment by rbozan** [comment]
> Hello @rbozan ,
> 
> I played around with Svelte and I seem to be able to partially work around how it works. [Check out this StackBlitz I've created.](https://stackblitz.com/edit/vitejs-vite-iuyro1?file=src%2FApp.svelte) It's not a very elegant solution but I guess that it can be wrapped with a svelte component that will take the start and end node and show the path.
> 

Hey @tarkant, it's been a year and I've tried your code again that you uploaded on Stackblitz but there's just two problems which I'll describe here. I've added workarounds for them myself (if anyone needs them).

I've adjusted your Stackblitz to demonstrate the problem (there's a line where I added a margin to a div, App.svelte line 63):
https://stackblitz.com/edit/vitejs-vite-dzkfre?file=src%2FApp.svelte

As you can see the svgElement could have been offset by other elements, but your method assumes that there's no offset at all, probably because it was created with the assumption that svgElement should be a direct child of the `body` element.

The other problem is, when you resize the window it should recalculate the lines because the offsets could differ.

The solutions are:
1. `<svelte:window on:resize={recalculate} />`
2. The div of the svgContainer should use something like a portal. I'm using `svelte-portal` for this. The code I'm currently using is:
```ts
<div
	class="svgContainer pointer-events-none -z-10 {svgContainerClass}"
	bind:this={svgContainer}
	use:portal={'body'}
>
```

Thanks again.
