### ISSUE TITLE
.update()

### ISSUE THREAD

**Issue by calumk** [tarkant/svg-dom-arrows#35]
Is there already, or could you add, an .update() to update the line if the position of the start/end element moves?

Im thinking of a draggable flowchart type situation

**Comment by calumk** [comment]
Yes that's perfect thanks, sorry I missed that in the changelog 

Recalculate is a slightly odd choice of word, it implies something more mathmatic...

Perhaps .redraw() ?

**Comment by tarkant** [comment]
Hello again @calumk , I've bumped the package to [v2.1.5](https://www.npmjs.com/package/svg-dom-arrows/v/2.1.5) with the new method `redraw()` and set `recalculate()` to deprecated to avoid breaking changes for the moment. I'll get rid of it in the next minor.

Please don't hesitate to create another issue if you need anything and thanks again for your valuable feedback!
