### ISSUE TITLE
SVG ArcPath line to always face down 

### ISSUE THREAD

**Issue by jjzhang1996** [tarkant/svg-dom-arrows#37]
Hi,

is it possible with current options to always set the line to be face down ? 

![Screenshot 2023-11-12 at 21 34 33](https://github.com/tarkant/svg-dom-arrows/assets/15787568/e459cbf8-c0f4-440f-883d-0bf774c9b7f1)

like in this case ? 
![Screenshot 2023-11-12 at 21 35 19](https://github.com/tarkant/svg-dom-arrows/assets/15787568/2e9089a6-933d-41af-af53-826679600af6)

**Comment by tarkant** [comment]
Hello @jjzhang1996 thanks for your feedback. Have you tried `CurvyPath` or `ArcPath` ? They might be better for your use case.

Kind regards.

**Comment by tarkant** [comment]
Hello again @jjzhang1996, just checking if my previous answer helped you solving your issue.
If you need something else please don't hesitate to reach out :) .
