### ISSUE TITLE
Not clear how to add custom path

### ISSUE THREAD

**Issue by silvaDominic** [tarkant/svg-dom-arrows#40]
In [this section](https://github.com/tarkant/svg-dom-arrows?tab=readme-ov-file#adding-another-path-style-) about adding custom paths, it's not clear if "add" refers to the project/repository or to the dependency folder (within `node_modules`) used in an actual project. Obviously, I don't want to be modifying a node module. At the same time I don't want add a custom path to this project just for my usecase.

Am I missing something?

**Comment by tarkant** [comment]
Hello @silvaDominic, I will have to rewrite the section to make it clear, the process I describe is more for people who want to contribute with another path style.
If you want to make a path in your own project, it's still straightforward, you create your `PathFileExample.ts` and inside you will need to just extend the `Path` class. I've created an example in this [StackBlitz](https://stackblitz.com/edit/create-custom-svg-dom-arrows-paths?file=src%2FMyPaths%2FCustomPath.ts).
Hope this helps :) .
