### ISSUE TITLE
TypeScript types are missing from NPM package

### ISSUE THREAD

**Issue by unitythemaker** [tarkant/svg-dom-arrows#47]
Hi! It seems like #29 is still valid. I am using ``v2.2.2`` and editor cannot find the declarations. Because the npm module doesn't seem to have them:
![image](https://github.com/user-attachments/assets/d8936bb4-412b-45c1-b310-0f236df34489)

**Comment by tarkant** [comment]
Hello @unitythemaker thank you for letting me know! I suspect I've messed up something in my webpack config. I'll check it ASAP and keep you updated.
Kind regards.

**Comment by tarkant** [comment]
Circling back to you @unitythemaker, I've just published [v2.3.0](https://www.npmjs.com/package/svg-dom-arrows/v/2.3.0) with the fix. The TS types are back.
Let me know if it's all good.
Thanks again for your report and kind regards.

**Comment by unitythemaker** [comment]
Thank you so much! Yeah, it works now.

**Comment by tarkant** [comment]
Awesome, please don't hesitate to open an issue if you need anything else.
Best regards.
